/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gameboy.glb --transform --shadows 
Files: public/models/gameboy.glb [16.72KB] > C:\Users\DylanLimTechpass.ACI_Laptop.000\Desktop\Github\dylxnlim.github.io\gameboy-transformed.glb [4.02KB] (76%)
*/

import React, { useRef, useState } from 'react'
import { Center, useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'

export default function Gameboy({ zoomed, onZoomComplete, ...props }) {
  const { size } = useThree()
  const isMobile = size.width < 768
  const finalScale = isMobile ? 0.5 : 1

  const { nodes, materials } = useGLTF('/models/gameboy-transformed.glb')
  const groupRef = useRef()
  const hasTriggered = useRef(false);
  const [lookTarget] = useState(() => new THREE.Vector3(0, 0, 0))
  
  useFrame((state, delta) => {
    if (!groupRef.current) return

    if (!zoomed) {
      hasTriggered.current = false;
      groupRef.current.rotation.y = (groupRef.current.rotation.y + delta * 2) % (Math.PI * 2);

      const idleCamPos = new THREE.Vector3(0, 0, 5);
      const idleLookAt = new THREE.Vector3(0, 0, 0);

      state.camera.position.lerp(idleCamPos, 0.05);
      lookTarget.lerp(idleLookAt, 0.05);
      state.camera.lookAt(lookTarget);
    } else if (zoomed) {
      // --- ZOOMED SEQUENCE ---
      // 1. Rotate to face camera
      groupRef.current.rotation.y = THREE.MathUtils.lerp(
        groupRef.current.rotation.y, 
        0, 
        0.1 
      )
      const isFacingFront = Math.abs(groupRef.current.rotation.y) < 0.1
      
      // 2. Zoom into screen
      if (isFacingFront) {
        lookTarget.lerp(new THREE.Vector3(0, 0.35, 0), 0.09)
        
        // Ensure camera looks at the screen height
        state.camera.position.lerp(new THREE.Vector3(0, 0.35, 0.5), 0.09)
        state.camera.lookAt(lookTarget)

        // Check if camera is close enough to screen for transition to start
        const distance = state.camera.position.distanceTo(new THREE.Vector3(0, 0.35, 0.6));
        if (distance < 0.12 && !hasTriggered.current) {
          hasTriggered.current = true;
          onZoomComplete();
        }
      }
    }
  })
  return (
    <group ref={groupRef} scale={finalScale} {...props} dispose={null}>
      <Center>
        <group rotation={[0, Math.PI / 2, 0]}>
          <mesh 
            castShadow 
            receiveShadow 
            geometry={nodes.Object_5.geometry} 
            material={materials.material_0}
          />
        </group>
      </Center>
    </group>
  )
}

useGLTF.preload('/models/gameboy-transformed.glb')
